### ISSUE TITLE
Correct value to set CFG_INT_TRACE_LEVEL_MIN

### ISSUE THREAD

**Issue by theta3** [microsoft/cpp_client_telemetry#1002]
# Is your question about how to consume a C++ library? 
Yes

Looking at `cpp_client_telemetry\lib\pal\DebugTrace.hpp`:

``````
 enum LogLevel {
        Error = 1,
        Warning = 2,
        Info = 3,
        Detail = 4
    };

    namespace detail {
        extern LogLevel g_logLevel;
        extern void log(LogLevel level, char const* component, char const* fmt, ...);
    } // namespace detail
``````
and
``````
#define MATSDK_LOG_ENABLED_(level_)   (PAL::detail::g_logLevel >= (level_))
``````

If I want to log `Error`, `Warning` and `Info`, which value should I use for `CFG_INT_TRACE_LEVEL_MIN`? Shouldn't it be `<=` and not the other way around?

**Comment by lalitb** [comment]
> If I want to log Error, Warning and Info, which value should I use for CFG_INT_TRACE_LEVEL_MIN

CFG_INT_TRACE_LEVEL_MIN should be 3 to log for Error, Warning, and Info. `<=` is the correct operator to achieve that.

**Comment by theta3** [comment]
Thanks. That makes sense
