### ISSUE TITLE
"pages build and deployment" action is continuously failing

### ISSUE THREAD

**Issue by sid-dahiya** [microsoft/cpp_client_telemetry#1004]
**Describe your environment.** 
All commits to main branch trigger `pages build and deployment` action. This action is continuously failing as it is not able to checkout the modules subrepo.

**Steps to reproduce.**
Push any commit to main branch.

**What is the expected behavior?**
`pages build and deployment` action succeeds.

**What is the actual behavior?**
The build step of the action is failing because it is not able to checkout the modules submodule. As an example from [this run](https://github.com/microsoft/cpp_client_telemetry/runs/5614314906?check_suite_focus=true):
>   Error: fatal: repository 'https://github.com/microsoft/cpp_client_telemetry_modules.git/' not found
  Error: fatal: clone of 'https://github.com/microsoft/cpp_client_telemetry_modules.git' into submodule path '/home/runner/work/cpp_client_telemetry/cpp_client_telemetry/lib/modules' failed
  Failed to clone 'lib/modules'. Retry scheduled
  Cloning into '/home/runner/work/cpp_client_telemetry/cpp_client_telemetry/third_party/googletest'...
  Cloning into '/home/runner/work/cpp_client_telemetry/cpp_client_telemetry/tools/vcpkg'...
  Cloning into '/home/runner/work/cpp_client_telemetry/cpp_client_telemetry/lib/modules'...
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/microsoft/cpp_client_telemetry_modules.git/' not found
  Error: fatal: clone of 'https://github.com/microsoft/cpp_client_telemetry_modules.git' into submodule path '/home/runner/work/cpp_client_telemetry/cpp_client_telemetry/lib/modules' failed
  Failed to clone 'lib/modules' a second time, aborting
  Error: The process '/usr/bin/git' failed with exit code 1

**Additional context.**
One solution might be to continue on error for the checkout step.

**Comment by lalitb** [comment]
I would prefer to disable github-pages (which would disable this action too) once #999 is merged.

**Comment by lalitb** [comment]
Github pages are disabled, the action shouldn't trigger anymore
![gh-pages](https://user-images.githubusercontent.com/1196320/161823706-f247b557-11c8-47e3-a173-3d2ea68b71c6.JPG)
