### ISSUE TITLE
Null pointer exception when using multiple Logger instances on Android

### ISSUE THREAD

**Issue by robertwernsman** [microsoft/cpp_client_telemetry#1022]
**Describe your environment.** 
SDK version: 1DS C++ SDK v3.5.321
Platform: Android 
OS Version: 11

**Steps to reproduce.**
I'm working on adding a 2nd LogManager instance to our Android java serivce. I'm running into an issue that wasn't happening with my single LogManager instance. I am able to successfully use both loggers as expected, but during my next service execution I get a Null Pointer Exception. After I crash from this exception, my service works correctly again (once). This repeats - every other execution seems to fail. I found that I can ensure each periodic execution works correctly if I manually kill the process after it completes, but this obviously isn't a solution. This leads me to believe something isn't getting cleanly 'closed'. 

**What is the expected behavior?**
I expect my service to get a Logger that is non-null. I was able to get the Logger previously and close/flush/flushAndTeardown successfully.

**What is the actual behavior?**
```
2022-06-08 12:11:40.827 15815-16345/? E/AndroidRuntime: FATAL EXCEPTION: TelemetryJob.Looper
    Process: com.microsoft.surface.telem, PID: 15815
    java.lang.NullPointerException: Null native logger pointer
        at com.microsoft.applications.events.LogManagerProvider$LogManagerImpl.getLogger(LogManagerProvider.java:34)
        at com.microsoft.surface.telem.TelemetryService$RunnableTelemetryWorker.startTelemetry(TelemetryService.java:435)
        at com.microsoft.surface.telem.TelemetryService$RunnableTelemetryWorker.run(TelemetryService.java:207)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Additional context.**
I'm initializing my two LogManager/Logger instances like this: 
```
            // Initialize general logger
            ILogManager generalLogManager = LogManagerProvider.createLogManager(config);
            ILogger generalLogger = generalLogManager.getLogger(token, "general_logger", "");

            // Initialize critical logger
            ILogManager criticalLogManager = LogManagerProvider.createLogManager(criticalConfig);
            ILogger criticalLogger = criticalLogManager.getLogger(token, "critical_logger", "");
```

Then at the end, I close(), flush(), and flushAndTeardown() like this: 

```
            Log.d(TAG, "Closing loggers...");
            surfaceEventLogger.generalLogManager.close();
            surfaceEventLogger.criticalLogManager.close();

            // Catch issues with the flushAndTeardown command producing illegal status values
            try {
                Log.d(TAG, "Flushing events...");
                surfaceEventLogger.generalLogManager.flush();
                surfaceEventLogger.generalLogManager.flushAndTeardown();
                surfaceEventLogger.criticalLogManager.flush();
                surfaceEventLogger.criticalLogManager.flushAndTeardown();
            } catch (java.lang.IllegalArgumentException e) {
                Log.e(TAG,"Failed during flushAndTeardown: Exception: " + e.getLocalizedMessage());
                Log.e(TAG,"Failed during flushAndTeardown: ",e);
            }
            Log.d(TAG, "Finished!");
            jobFinished(jobParameters, false);
            Log.d(TAG, "jobFinished() called");
```

**Since I only get this exception after a successful execution, maybe I'm not closing something correctly? This is the example I'm using for working with multiple loggers. Unfortunately, it doesn't show me how to clean up / tear down the instances.**
 https://github.com/microsoft/cpp_client_telemetry/blob/7ba0de055dea6d8f21e4b6bf9cc9e20eceaadfab/lib/android_build/app/src/androidTest/java/com/microsoft/applications/events/maesdktest/LogManagerDDVUnitTest.java#L105

**Comment by lalitb** [comment]
@robertwernsman - Can you ensure you are setting CFG_STR_FACTORY_NAME and CFG_STR_FACTORY_HOST in config:

```
logConfiguration.set(LogConfigurationKey.CFG_STR_FACTORY_NAME, <name1>);
logConfiguration.set(LogConfigurationKey.CFG_STR_FACTORY_HOST, <name2>);
```

The loggers are stored in map against host/name key, and if just to ensure they are not getting overwritten if these values are not set properly.

**Comment by robertwernsman** [comment]
Thanks for the suggestion, I was indeed not setting those values for either config. I tried adding that with unique strings for each logger, and still have my error unfortunately. It does seem to be related to the LogManagerImpl::GetLogger(...) implementation where it looks up the existing logger (that has already been closed): https://github.com/microsoft/cpp_client_telemetry/blob/1fd167fa1595853cd423f9d3229915ad0092a09b/lib/api/LogManagerImpl.cpp#L653


However, a hack I tried ended up fixing my exception:
```
// Initialize general logger
ILogManager generalLogManager = LogManagerProvider.createLogManager(config);
ILogger generalLogger = generalLogManager.getLogger(token, java.util.UUID.randomUUID().toString(), java.util.UUID.randomUUID().toString());

// Initialize critical logger
ILogManager criticalLogManager = LogManagerProvider.createLogManager(criticalConfig);
ILogger criticalLogger = criticalLogManager.getLogger(token, java.util.UUID.randomUUID().toString(), java.util.UUID.randomUUID().toString());
Log.d(TAG, "1DS init with weird strings such as: " + java.util.UUID.randomUUID().toString());
```

Not sure if this a 'good' solution or if it will cause problems, but the unique names seem to prevent our getLogger(...) call from finding old null Logger instances. Are there any drawbacks to using a random and unique name for the 'source' and/or 'scope' arguments?

**Comment by robertwernsman** [comment]
After adding some prints to understand where the SDK is returning null, I found that after we call flushAndTeardown(...), the m_alive boolean is set to false. This value never gets set to true again, so when we later call getLogger(...), we enter this condition which returns null: 

https://github.com/microsoft/cpp_client_telemetry/blob/eddf9b3c92f6ffee4d022d5286f307649543fcb4/lib/api/LogManagerImpl.cpp#L636

**How can we properly initialize these two loggers such than m_alive is set to true again? It seems like this constructor code needs to run again:** 
https://github.com/microsoft/cpp_client_telemetry/blob/eddf9b3c92f6ffee4d022d5286f307649543fcb4/lib/api/LogManagerImpl.cpp#L148

**Comment by robertwernsman** [comment]
After reading some docs about LogManagerProvider, it sounds like I can get an 'Exclusive Log Manager' by specifying the _name_ and leaving the _host_ blank in the config. I left my initialization code the same, added this entry into my config, and left my teardown code the same. The below setup seems to be working. **Will there be any issues with using a randomly generated value for CFG_STR_FACTORY_NAME?**


Current working code:

Entry added to configs
```
config.set(LogConfigurationKey.CFG_STR_FACTORY_NAME, java.util.UUID.randomUUID().toString());

criticalConfig.set(LogConfigurationKey.CFG_STR_FACTORY_NAME, java.util.UUID.randomUUID().toString());
```


Initialization:
```
// Initialize general logger
ILogManager generalLogManager = LogManagerProvider.createLogManager(config);
ILogger generalLogger = generalLogManager.getLogger(token, "general_logger", "");

// Initialize critical logger
ILogManager criticalLogManager = LogManagerProvider.createLogManager(criticalConfig);
ILogger criticalLogger = criticalLogManager.getLogger(token, "critical_logger", "");
```

Teardown:
```
            Log.d(TAG, "Closing loggers...");
            surfaceEventLogger.generalLogManager.close();
            surfaceEventLogger.criticalLogManager.close();

            // Catch issues with the flushAndTeardown command producing illegal status values
            try {
                Log.d(TAG, "Flushing events...");
                surfaceEventLogger.generalLogManager.flush();
                surfaceEventLogger.generalLogManager.flushAndTeardown();
                surfaceEventLogger.criticalLogManager.flush();
                surfaceEventLogger.criticalLogManager.flushAndTeardown();
            } catch (java.lang.IllegalArgumentException e) {
                Log.e(TAG,"Failed during flushAndTeardown: Exception: " + e.getLocalizedMessage());
                Log.e(TAG,"Failed during flushAndTeardown: ",e);
            }
            Log.d(TAG, "Finished!");
            jobFinished(jobParameters, false);
            Log.d(TAG, "jobFinished() called");
```

**Comment by lalitb** [comment]
> Will there be any issues with using a randomly generated value for CFG_STR_FACTORY_NAME?

I don't think there should be any issue as long as the `name` is unique.

**Comment by lalitb** [comment]
>  leaving the `host` blank in the config

This is interesting, as the [MultipleLogManagersTests.cpp](https://github.com/microsoft/cpp_client_telemetry/blob/main/tests/functests/MultipleLogManagersTests.cpp) test validates using unique values of `host` and `name`.

**Comment by lalitb** [comment]
@robertwernsman  - Do you have further update on the issue, in case you were able to debug this further?

**Comment by lalitb** [comment]
@robertwernsman  - Checking if you have resolved this issue, or any further updates? Would like to close the issue if it is no longer valid.

**Comment by lalitb** [comment]
@robertwernsman  - Can you give us some repro for the C++/Android, we can debug this further. As we don't see any crash in our CI unit tests.

**Comment by lalitb** [comment]
Closing as stale - please reopen with the repro for C++/Android for us to debug it further.
