### ISSUE TITLE
Make definitions in mat.h forward declarable

### ISSUE THREAD

**Issue by stephenatwork** [microsoft/cpp_client_telemetry#1051]
mat.h (The C ABI-stable interface) uses the following style to declare structs

```
typedef struct {
} foo;
```

This means that these structs cannot be forward declared. This has the unfortunate consequence that to declare a function such as `DoLog(evt_prop[] props)`, one has to #include mat.h rather than a simple forward declaration to maintain include hygiene.

A common solution is to give the anonymous structures a name (sometimes with an "_" prefix)
```
// prefix
typedef struct _foo { 
} foo;

// another common option is to use the same name since they're in different symbol namespaces.
typedef struct foo { 
} foo;
```

Then we could write `struct _evt_prop; DoLog(_evt_prop[] props)`

**Comment by lalitb** [comment]
closes with #1052
