### ISSUE TITLE
iOS SDK crashes when parsing the config in LogManagerFactory

### ISSUE THREAD

**Issue by pathayan** [microsoft/cpp_client_telemetry#1076]
**Describe your environment.** 
Pod version 3.6.187

**Steps to reproduce.**
We cannot reproduce this issue ourselves. However, as we started rolling out logging with a config, we started seeing crashes in App Center. 

**What is the expected behavior?**
No app crashes

**What is the actual behavior?**
We see crashes with the following stack trace: 

```
OneDriveShared
Microsoft::Applications::Events::Variant::assign(Microsoft::Applications::Events::Variant const&) __tree:81
OneDriveShared
Microsoft::Applications::Events::Variant::Variant(Microsoft::Applications::Events::Variant const&) VariantType.hpp:82
OneDriveShared
Microsoft::Applications::Events::LogManagerFactory::parseConfig(Microsoft::Applications::Events::ILogConfiguration&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) VariantType.hpp:81
OneDriveShared
Microsoft::Applications::Events::LogManagerFactory::lease(Microsoft::Applications::Events::ILogConfiguration&) LogManagerFactory.cpp:116
OneDriveShared
Microsoft::Applications::Events::LogManagerProvider::Get(Microsoft::Applications::Events::ILogConfiguration&, Microsoft::Applications::Events::status_t&) LogManagerFactory.hpp:95
OneDriveShared
ODWLogManager.loggerWithTenant:source:withConfig: LogManagerProvider.hpp:112
OneDriveShared
function signature specialization <Arg[3] = Dead> of OneDriveCore.ODWLoggerProvider.(createLogger in _4DC64044BA0DA6B5562C350C717336F3)(withConfiguration: OneDriveCore.OneDSLoggerConfiguration, tenantId: Swift.String, source: Swift.String) -> __C.ODWLogger?
```

**Additional context.**
There are no crashes when we call _ODWLogManager.logger(withTenant: tenant, source: source)_ instead. We started rolling out calling _ODWLogManager.logger(withTenant: tenant, source: source, withConfig: config)_ instead for EUDB support. That rollout is now blocked due to this crash. 

This code path is exercised very frequently, and there are no crashes the vast majority of the time. But sometimes it does crash and this would likely be our top crash if we fully rolled this out.

**Comment by lalitb** [comment]
@pathayan athayan `config` object seems to be going out of scope, while we are passing reference to it to ODWLogManager::loggerWithTenant(). 
Please review the calling code, on how the `config` object is being managed.

**Comment by pathayan** [comment]
@lalitb the caller does not move `config` out of scope until the `ODWLogManager` returns.

`       let config = ODWLogConfiguration.getCopy() ?? ODWLogConfiguration()
        config.setHost(configuration.host)
        config.set(OneDSLoggerConfigurationConstants.name, withValue: configuration.name)
        config.set(OneDSLoggerConfigurationConstants.version, withValue: configuration.version)
        config.set(OneDSLoggerConfigurationConstants.eventCollectorUri, withValue: configuration.collectorUrl)
        
        // Get a logger from SDK
        guard let logger = odwLogManager.logger(withTenant: tenantId, source: source, withConfig: config)  else {
            assertFailAndRecord("Failed to get logger for source \(source), collectorUrl: \(configuration.collectorUrl)", identifier: "T4jM.zygL", owner: "pathayan")
            return nil
        }`

The `odwLogManager` instance just makes a passthrough call to the equivalent `ODWLogManager` method.

**Comment by lalitb** [comment]
This is  crash during logger initialization, different from the earlier crashes we observed during shutdown and what is planned for v4 release in this semester. Also, seeing it for the first time.

@pathayan  - I am assigning it to you, as this is not an issue with 1DS C++ layer. Please debug the 1DS obj-c layer, along with your application to see what is causing the issue. And contribute the fix if it is required.

**Comment by pathayan** [comment]
Update: as mentioned previously, I used locks to ensure two separate threads weren't calling my above code at the same time. This fixed the issue.
