### ISSUE TITLE
Android crash on LogManager::UploadNow()

### ISSUE THREAD

**Issue by abuhsayem** [microsoft/cpp_client_telemetry#1202]
**Describe your environment.** 
On Android, a crash occurs when the following code is executed sequentially
LogManagerProvider::CreateLogManager()
<< Events generated >>
LogManager::UploadNow()
LogManager::Release();
The crash occurs when LogManager::UploadNow() is called
In C++, from debugger I could trace the crash at 'cpp_client_telemetry/lib/offline/OfflineStorage_Room.cpp' in destructor ' OfflineStorage_Room::~OfflineStorage_Room()' at line 148 'ConnectedEnv env(s_vm);'
In Android crash dump, the crash seems to be happening in Java layer in OfflineRoom.getRecordCount(OfflineRoom.java:200)
cpp_client_telemetry/lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/OfflineRoom.java

**Steps to reproduce.**
Steps mentioned above

**What is the expected behavior?**
No crash

**What is the actual behavior?**
Crash

**Additional context.**

**Comment by lalitb** [comment]
@abuhsayem  - Do you have the crash stacktrace and stacktrace for all other threads at that time?

**Comment by abuhsayem** [comment]
Updated the steps to reproduce and attached Android crash dump.

[UploadNow_crash_Android.txt](https://github.com/microsoft/cpp_client_telemetry/files/12554613/UploadNow_crash_Android.txt)

**Comment by lalitb** [comment]
So, the crash is happening during UploadNow, and not FlushAndTearDown? If so, can you please update the title of the issue.

Also from the crash dump: 
`Cannot access database on the main thread since it may potentially lock the UI for a long period of time`

This seems to be expected behavior - Android OS doesn't allow long running processes (e.g., DB access) on main UI thread. You may have to investigate how this can be executed asynchronously using AsyncTask or any other mechanism within App code.

**Comment by abuhsayem** [comment]
attached stacktrace in C++ code
[c++_crash_Android.txt](https://github.com/microsoft/cpp_client_telemetry/files/12590945/c%2B%2B_crash_Android.txt)

**Comment by abuhsayem** [comment]
Since, the crash happens in 'OfflineRoom.getRecordCount(int latency)' function as it starts a SQLite query (in StorageRecordDao.java)
https://github.com/microsoft/cpp_client_telemetry/tree/main/lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/OfflineRoom.java

I have replaced this function to use AsyncTask and wait for completion; the crash does not occur with it (attached code)
[OfflineRoom.txt](https://github.com/microsoft/cpp_client_telemetry/files/12591640/OfflineRoom.txt)

**Comment by anod** [comment]
AsyncTask is deprecated.  Like error suggest you shouldn't call those methods on the main thread, which I assume everyone that uses this SDK Android & Room already does. I think this should be better documented

I use the following wrapper:

```kotlin
class SingleThreadLogger(
        private val appCoroutineScope: AppCoroutineScope,
        private val logger: Logger
) : Logger {
    // To avoid synchronization on logger use same single thread context
    private val loggerContext = Executors.newSingleThreadExecutor().asCoroutineDispatcher()

    override fun initialize() {
        appCoroutineScope.launch(loggerContext) {
            logger.initialize()
        }
    }

    override fun reconfigure(config: Map<String, String?>) {
        appCoroutineScope.launch(loggerContext) {
            logger.reconfigure(config)
        }
    }

    override fun suspend() {
        appCoroutineScope.launch(loggerContext) {
            logger.suspend()
        }
    }

    override fun resume() {
        appCoroutineScope.launch(loggerContext) {
            logger.resume()
        }
    }

    override fun writeEvent(item: Telemetry.Event) {
        appCoroutineScope.launch(loggerContext) {
            logger.writeEvent(item)
        }
    }
}
````

**Comment by abuhsayem** [comment]
In 'UTel SDK', we use '1DS SDK' C++ code to create the LogManager. For Android, we have Java wrapper that uses JNI to use the C++ code.

DefaultEventSink.java -> JNIDefaultEventSink.cpp -> DefaultEventSink.cpp (LogManager is created in DefaultEventSink.cpp)
"OfflineRoom.connectContext(context)" is called once in DefaultEventSink.java and not for every object.

In this case, would you recommend using AppCoroutineScope with Executors.newSingleThreadExecutor() for every DefaultEventSink java object or it should it be used in the Android app!

**Comment by anod** [comment]
On which thread LogManager is created ? it shouldn't be called on main, since OfflineRoom runs queries in constructor,
so I would expect the same thread to use for teardown the LogManager

**Comment by abuhsayem** [comment]
We donot use threading to create LogManager, hence it is created on main.

For clarification, I have the following queries regarding Android:
a) The crash is not seen when 'Executors.newSingleThreadExecutor()' is used in Java layer to call C++ 'LogManager::UploadNow()' using JNI - is this implementation okay or a new thread should be created for each LogManager
b) OfflineRoom & HttpClient.java should be run on main or new thread

**Comment by abuhsayem** [comment]
Using separate thread does not cause crash
