### ISSUE TITLE
./build-ios.sh release failed with iOS17.4 incompatible errors

### ISSUE THREAD

**Issue by jacobjiangwei** [microsoft/cpp_client_telemetry#1283]
**Describe your environment.** Describe any aspect of your environment relevant to the problem, including your SDK version, platform, OS version, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main brach.
iOS 17.4, macOS14.5

**Steps to reproduce.**
Describe exactly how to reproduce the error. Include a code sample if applicable.
./build-ios.sh release 

**What is the expected behavior?**
What did you expect to see?

./build-ios.sh release successfully

**What is the actual behavior?**
What did you see instead?
failed with errors, see below logs

**Additional context.**

CMake Generate step failed.  Build files cannot be regenerated correctly.
[  1%] Building CXX object lib/CMakeFiles/mat.dir/decorators/BaseDecorator.cpp.o
[  2%] Building CXX object lib/CMakeFiles/mat.dir/packager/BondSplicer.cpp.o
[  3%] Building CXX object lib/CMakeFiles/mat.dir/packager/Packager.cpp.o
[  3%] Building CXX object lib/CMakeFiles/mat.dir/callbacks/DebugSource.cpp.o
[  4%] Building CXX object lib/CMakeFiles/mat.dir/bond/BondSerializer.cpp.o
[  5%] Building CXX object lib/CMakeFiles/mat.dir/filter/EventFilterCollection.cpp.o
[  6%] Building CXX object lib/CMakeFiles/mat.dir/tpm/TransmitProfiles.cpp.o
[  7%] Building CXX object lib/CMakeFiles/mat.dir/tpm/TransmissionPolicyManager.cpp.o
[  7%] Building CXX object lib/CMakeFiles/mat.dir/tpm/DeviceStateHandler.cpp.o
[  8%] Building CXX object lib/CMakeFiles/mat.dir/system/EventProperty.cpp.o
[  9%] Building CXX object lib/CMakeFiles/mat.dir/system/TelemetrySystem.cpp.o
[ 10%] Building CXX object lib/CMakeFiles/mat.dir/system/EventProperties.cpp.o
[ 11%] Building CXX object lib/CMakeFiles/mat.dir/compression/HttpDeflateCompression.cpp.o
[ 11%] Building CXX object lib/CMakeFiles/mat.dir/api/AllowedLevelsCollection.cpp.o
[ 12%] Building CXX object lib/CMakeFiles/mat.dir/api/LogManager.cpp.o
[ 13%] Building CXX object lib/CMakeFiles/mat.dir/api/ContextFieldsProvider.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/mat.dir/api/LogManagerImpl.cpp.o
[ 15%] Building CXX object lib/CMakeFiles/mat.dir/api/LogSessionData.cpp.o
[ 15%] Building CXX object lib/CMakeFiles/mat.dir/api/Logger.cpp.o
[ 16%] Building CXX object lib/CMakeFiles/mat.dir/api/LogManagerProvider.cpp.o
[ 17%] Building CXX object lib/CMakeFiles/mat.dir/api/CorrelationVector.cpp.o
[ 18%] Building CXX object lib/CMakeFiles/mat.dir/api/LogConfiguration.cpp.o
[ 19%] Building CXX object lib/CMakeFiles/mat.dir/api/AuthTokensController.cpp.o
[ 19%] Building CXX object lib/CMakeFiles/mat.dir/api/ILogConfiguration.cpp.o
[ 20%] Building CXX object lib/CMakeFiles/mat.dir/api/LogManagerFactory.cpp.o
[ 21%] Building CXX object lib/CMakeFiles/mat.dir/api/capi.cpp.o
[ 22%] Building CXX object lib/CMakeFiles/mat.dir/api/DataViewerCollection.cpp.o
[ 23%] Building CXX object lib/CMakeFiles/mat.dir/utils/FileUtils.cpp.o
[ 23%] Building CXX object lib/CMakeFiles/mat.dir/utils/Utils.cpp.o
[ 24%] Building CXX object lib/CMakeFiles/mat.dir/utils/StringUtils.cpp.o
[ 25%] Building CXX object lib/CMakeFiles/mat.dir/utils/ZlibUtils.cpp.o
[ 26%] Building CXX object lib/CMakeFiles/mat.dir/pal/InformationProviderImpl.cpp.o
[ 27%] Building CXX object lib/CMakeFiles/mat.dir/http/HttpClient_CAPI.cpp.o
[ 27%] Building CXX object lib/CMakeFiles/mat.dir/http/HttpClientManager.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/mat.dir/http/HttpRequestEncoder.cpp.o
[ 29%] Building CXX object lib/CMakeFiles/mat.dir/http/HttpResponseDecoder.cpp.o
[ 30%] Building CXX object lib/CMakeFiles/mat.dir/http/HttpClientFactory.cpp.o
[ 31%] Building CXX object lib/CMakeFiles/mat.dir/stats/Statistics.cpp.o
[ 31%] Building CXX object lib/CMakeFiles/mat.dir/stats/MetaStats.cpp.o
[ 32%] Building CXX object lib/CMakeFiles/mat.dir/offline/StorageObserver.cpp.o
[ 33%] Building CXX object lib/CMakeFiles/mat.dir/offline/OfflineStorageFactory.cpp.o
[ 34%] Building CXX object lib/CMakeFiles/mat.dir/offline/MemoryStorage.cpp.o
[ 35%] Building CXX object lib/CMakeFiles/mat.dir/offline/OfflineStorage_SQLite.cpp.o
[ 35%] Building CXX object lib/CMakeFiles/mat.dir/offline/OfflineStorageHandler.cpp.o
[ 36%] Building CXX object lib/CMakeFiles/mat.dir/offline/LogSessionDataProvider.cpp.o
[ 37%] Building CXX object lib/CMakeFiles/mat.dir/backoff/IBackoff.cpp.o
[ 38%] Building CXX object lib/CMakeFiles/mat.dir/pal/PAL.cpp.o
[ 39%] Building CXX object lib/CMakeFiles/mat.dir/pal/TaskDispatcher_CAPI.cpp.o
[ 39%] Building CXX object lib/CMakeFiles/mat.dir/pal/WorkerThread.cpp.o
[ 40%] Building CXX object lib/CMakeFiles/mat.dir/pal/posix/sysinfo_utils_apple.cpp.o
[ 41%] Building CXX object lib/CMakeFiles/mat.dir/pal/posix/sysinfo_utils_ios.mm.o
[ 42%] Building CXX object lib/CMakeFiles/mat.dir/pal/posix/DeviceInformationImpl.cpp.o
[ 43%] Building CXX object lib/CMakeFiles/mat.dir/pal/posix/SystemInformationImpl.cpp.o
[ 43%] Building CXX object lib/CMakeFiles/mat.dir/pal/posix/sysinfo_sources.cpp.o
[ 44%] Building CXX object lib/CMakeFiles/mat.dir/http/HttpClient_Apple.mm.o
[ 45%] Building CXX object lib/CMakeFiles/mat.dir/pal/posix/NetworkInformationImpl.mm.o
[ 46%] Building C object lib/CMakeFiles/mat.dir/__/third_party/Reachability/ODWReachability.m.o
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:98:36: error: 'SCNetworkReachabilityCreateWithName' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    SCNetworkReachabilityRef ref = SCNetworkReachabilityCreateWithName(NULL, [hostname UTF8String]);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:249:1: note: 'SCNetworkReachabilityCreateWithName' has been explicitly marked deprecated here
SCNetworkReachabilityCreateWithName             (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:111:36: error: 'SCNetworkReachabilityCreateWithAddress' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    SCNetworkReachabilityRef ref = SCNetworkReachabilityCreateWithAddress(kCFAllocatorDefault, (const struct sockaddr*)hostAddress);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:209:1: note: 'SCNetworkReachabilityCreateWithAddress' has been explicitly marked deprecated here
SCNetworkReachabilityCreateWithAddress          (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:207:8: error: 'SCNetworkReachabilitySetCallback' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(SCNetworkReachabilitySetCallback(self.reachabilityRef, TMReachabilityCallback, &context))
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:298:1: note: 'SCNetworkReachabilitySetCallback' has been explicitly marked deprecated here
SCNetworkReachabilitySetCallback                (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:210:12: error: 'SCNetworkReachabilitySetDispatchQueue' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
        if(SCNetworkReachabilitySetDispatchQueue(self.reachabilityRef, self.reachabilitySerialQueue))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:358:1: note: 'SCNetworkReachabilitySetDispatchQueue' has been explicitly marked deprecated here
SCNetworkReachabilitySetDispatchQueue           (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:224:13: error: 'SCNetworkReachabilitySetCallback' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
            SCNetworkReachabilitySetCallback(self.reachabilityRef, NULL, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:298:1: note: 'SCNetworkReachabilitySetCallback' has been explicitly marked deprecated here
SCNetworkReachabilitySetCallback                (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:242:5: error: 'SCNetworkReachabilitySetCallback' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    SCNetworkReachabilitySetCallback(self.reachabilityRef, NULL, NULL);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:298:1: note: 'SCNetworkReachabilitySetCallback' has been explicitly marked deprecated here
SCNetworkReachabilitySetCallback                (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:245:5: error: 'SCNetworkReachabilitySetDispatchQueue' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    SCNetworkReachabilitySetDispatchQueue(self.reachabilityRef, NULL);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:358:1: note: 'SCNetworkReachabilitySetDispatchQueue' has been explicitly marked deprecated here
SCNetworkReachabilitySetDispatchQueue           (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:291:9: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(!SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:303:8: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:324:8: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:355:5: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
        if(SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:368:6: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
        if (SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:382:6: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
        if (SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:413:8: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
14 errors generated.
make[2]: *** [lib/CMakeFiles/mat.dir/__/third_party/Reachability/ODWReachability.m.o] Error 1
make[1]: *** [lib/CMakeFiles/mat.dir/all] Error 2
make: *** [all] Error 2
[  1%] Building C object lib/CMakeFiles/mat.dir/__/third_party/Reachability/ODWReachability.m.o
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:98:36: error: 'SCNetworkReachabilityCreateWithName' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    SCNetworkReachabilityRef ref = SCNetworkReachabilityCreateWithName(NULL, [hostname UTF8String]);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:249:1: note: 'SCNetworkReachabilityCreateWithName' has been explicitly marked deprecated here
SCNetworkReachabilityCreateWithName             (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:111:36: error: 'SCNetworkReachabilityCreateWithAddress' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    SCNetworkReachabilityRef ref = SCNetworkReachabilityCreateWithAddress(kCFAllocatorDefault, (const struct sockaddr*)hostAddress);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:209:1: note: 'SCNetworkReachabilityCreateWithAddress' has been explicitly marked deprecated here
SCNetworkReachabilityCreateWithAddress          (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:207:8: error: 'SCNetworkReachabilitySetCallback' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(SCNetworkReachabilitySetCallback(self.reachabilityRef, TMReachabilityCallback, &context))
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:298:1: note: 'SCNetworkReachabilitySetCallback' has been explicitly marked deprecated here
SCNetworkReachabilitySetCallback                (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:210:12: error: 'SCNetworkReachabilitySetDispatchQueue' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
        if(SCNetworkReachabilitySetDispatchQueue(self.reachabilityRef, self.reachabilitySerialQueue))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:358:1: note: 'SCNetworkReachabilitySetDispatchQueue' has been explicitly marked deprecated here
SCNetworkReachabilitySetDispatchQueue           (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:224:13: error: 'SCNetworkReachabilitySetCallback' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
            SCNetworkReachabilitySetCallback(self.reachabilityRef, NULL, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:298:1: note: 'SCNetworkReachabilitySetCallback' has been explicitly marked deprecated here
SCNetworkReachabilitySetCallback                (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:242:5: error: 'SCNetworkReachabilitySetCallback' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    SCNetworkReachabilitySetCallback(self.reachabilityRef, NULL, NULL);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:298:1: note: 'SCNetworkReachabilitySetCallback' has been explicitly marked deprecated here
SCNetworkReachabilitySetCallback                (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:245:5: error: 'SCNetworkReachabilitySetDispatchQueue' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    SCNetworkReachabilitySetDispatchQueue(self.reachabilityRef, NULL);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:358:1: note: 'SCNetworkReachabilitySetDispatchQueue' has been explicitly marked deprecated here
SCNetworkReachabilitySetDispatchQueue           (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:291:9: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(!SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:303:8: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:324:8: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:355:5: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
        if(SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:368:6: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
        if (SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:382:6: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
        if (SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
/Users/jacob/work/cpp_client_telemetry/third_party/Reachability/ODWReachability.m:413:8: error: 'SCNetworkReachabilityGetFlags' is deprecated: first deprecated in iOS 17.4 [-Werror,-Wdeprecated-declarations]
    if(SCNetworkReachabilityGetFlags(self.reachabilityRef, &flags))
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       Use URLSession or NWConnection to create connections that dynamically handle changing networks. Use NWPathMonitor to enumerate available network interfaces.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:278:1: note: 'SCNetworkReachabilityGetFlags' has been explicitly marked deprecated here
SCNetworkReachabilityGetFlags                   (
^
14 errors generated.
make[2]: *** [lib/CMakeFiles/mat.dir/__/third_party/Reachability/ODWReachability.m.o] Error 1
make[1]: *** [lib/CMakeFiles/mat.dir/all] Error 2
make: *** [all] Error 2

**Comment by lalitb** [comment]
closing as duplicate to #1261

**Comment by jacobjiangwei** [comment]
@lalitb it's better to upgrade the home page status. it says iOS10+ all good, but it stops some version now.

so 1DS is not open for adoption for iOS? what's the alternatives?

**Comment by lalitb** [comment]
> so 1DS is not open for adoption for iOS?

@jacobjiangwei This issue was closed for #1261. 1DS should support iOS 17.4, macOS14.5, we need help from community to fix this issue.
