### ISSUE TITLE
Temporary path in Win32 needs to leverage GetTempPath2W when available

### ISSUE THREAD

**Issue by ankamat-msft** [microsoft/cpp_client_telemetry#1316]
Per recent documentation, GetTempPath2W() should be attempted before using GetTempPathW().

https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppathw#remarks

**Comment by ThomsonTan** [comment]
@ankamat-msft I did see the preference on `GetTempPath2W()` in the doc link you shared. Could you please add the link?
