### ISSUE TITLE
Remove warnings from header files

### ISSUE THREAD

**Issue by AmitEnoch** [microsoft/cpp_client_telemetry#221]
**Is your feature request related to a problem?**
If the header files are compiled with -Wall, many errors are generated due to unused variables and parameters.

**Describe the solution you'd like.**
clean up the unused params, or add explicit GCC pragmas to handle suppress these warning.

**Comment by maxgolov** [comment]
This issue has been resolved in latest: for all compilers we emit zero warnings in Un*x
