### ISSUE TITLE
Support concurrent access to a shared db file in OfflineStorage_SQLite

### ISSUE THREAD

**Issue by larvacea** [microsoft/cpp_client_telemetry#522]
Each instance of OfflineStorage_SQLite protects its writes with two forms of serialization:

- An exclusive mutex in the instance. No instance will ever try to start two transactions to its database at one time. This is not absolutely assured since the code separates mutex and smart-transaction-object, but at least at first inspection these are paired so the transaction object is instantiated inside the guard.
- A SQLite BEGIN EXCLUSIVE (immediate write) transaction.

So if one has:

- Multiple instances of LogManager, with multiple instances (therefore) of OfflineStorageHandler, with (therefore) multiple instances of OfflineStorage_SQLite, or
- Multiple database connections because some other odd component opens a connection on the database file, or
- Multiple processes sharing the database file,

then the BEGIN EXCLUSIVE statement can return SQLITE_BUSY.

- For Flush(), this will drop each SQLITE_BUSY record. We take a lock per record during flush.
- For GetAndReserveRecords(), this will immediately return false and the consumer functor will receive no records.

Fortunately we only use BEGIN EXCLUSIVE transactions, so we will not have a transaction deadlock to break. The GetAndReserveRecords() failure doesn't drop events, but may affect upload performance. SQLite has two built in busy handlers:

- For a fixed maximum timeout, the PRAGMA busy_timeout statement can set a timeout. There is C API equivalent.
- For a more nuanced retry strategy, sqlite3_busy_handler() will register a callback function to do whatever you like for retry strategy.

I'd like to propose using the built in busy handler support with a configurable timeout strategy, to try to avoid either OOM or data dropped on the floor in Flush(). Max shared the timeout/backoff retry he implemented in v1, and that seems like a reasonable approach here.

At least so far, it appears that androidx.room is already handling busy-retry for OfflineStorage_Room. If it has a fixed timeout limit, it's more than 1 second.

I also propose to add unit tests (truth be told, I wrote some already, which is how I discovered this behavior).

**Comment by maxgolov** [comment]
This issue is quite old. This was not a blocker for Duo. I'm removing myself from assignment.
Please take a look if this is still something that requires further investment.
Closing it, feel free to reopen if needed.
