### ISSUE TITLE
Query on SessionId

### ISSUE THREAD

**Issue by suryatn** [microsoft/cpp_client_telemetry#743]
When testing @larvacea's multiple log manager changes (pulling the recent master 03e246e4c0955e5f8707399f046a1a2212a92bb2), I observed that sessionId is getting logged as different for logSession() API.

As suggested earlier from your team, we are generating SessionId using `UUID.randomUUID().toString()` on our client during app start only once and setting it as global context using LogManager's `setContext(key, value, getOneDSPiiKind(PiiKind.NONE))` method. We are setting the same sessionId even on cloud switch scenario.
E.g sessionId generated on client = `591e1f85-c848-4ac4-b352-96e669a29d89` and this value gets appended to all events. However for session table using logSession API, the session_Id seems to be different `09c9dc06-7c24-dae8-d0f8-bfa4dacab128`. Please help in resolving this issue.

@maxgolov @larvacea @mkoscumb @sid-dahiya

**Comment by maxgolov** [comment]
I'm closing this issue, since I believe the question has been answered. Please reopen it if it's still a concern.
