### ISSUE TITLE
Not all paths in ODWLogManager flush/flushAndTeardown return a value

### ISSUE THREAD

**Issue by kindbe** [microsoft/cpp_client_telemetry#767]
Hit this trying to update a podspec to version 3.5.19:

    - ERROR | xcodebuild:  OneDsCppSdk.iOS/wrappers/obj-c/ODWLogManager.mm:191:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]

    - ERROR | xcodebuild:  OneDsCppSdk.iOS/wrappers/obj-c/ODWLogManager.mm:207:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]

flush and flushAndTeardown were modified to return an ODWStatus in #750 , but don't return anything in the 'catch' condition

**Comment by maxgolov** [comment]
It looks like we'd need re-release. Is this only those two places? What would be the best return value in this case?

**Comment by sid-dahiya** [comment]
I am seeing this linking failure without any changes at all when building obj-c wrapper:
```
[ 71%] Linking CXX executable sample
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ODWCommonDataContext", referenced from:
      objc-class-ref in main.mm.o
  "_OBJC_CLASS_$_ODWPrivacyGuard", referenced from:
      objc-class-ref in ODWLogger.mm.o
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[ODWReachability reachabilityWithAddress:] in libmat.a(ODWReachability.m.o)
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[ODWReachability reachabilityWithHostname:] in libmat.a(ODWReachability.m.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      -[ODWReachability isReachable] in libmat.a(ODWReachability.m.o)
      -[ODWReachability isReachableViaWiFi] in libmat.a(ODWReachability.m.o)
      -[ODWReachability connectionRequired] in libmat.a(ODWReachability.m.o)
      -[ODWReachability isConnectionOnDemand] in libmat.a(ODWReachability.m.o)
      -[ODWReachability isInterventionRequired] in libmat.a(ODWReachability.m.o)
      -[ODWReachability reachabilityFlags] in libmat.a(ODWReachability.m.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[ODWReachability startNotifier] in libmat.a(ODWReachability.m.o)
      -[ODWReachability stopNotifier] in libmat.a(ODWReachability.m.o)
  "_SCNetworkReachabilitySetDispatchQueue", referenced from:
      -[ODWReachability startNotifier] in libmat.a(ODWReachability.m.o)
      -[ODWReachability stopNotifier] in libmat.a(ODWReachability.m.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [sample] Error 1
make[1]: *** [CMakeFiles/sample.dir/all] Error 2
make: *** [all] Error 2
```

Are these related?

**Comment by maxgolov** [comment]
No, it's different. I think this one is due to recently added SCReachability for Mac OS X... actually, wait. We used to not have any network detection, now we have some and it's in Obj-C. Maybe we need to come up with a solution that allows to build again without network detection if Obj-C is off.

**Comment by maxgolov** [comment]
Probably related to this one #126
