### ISSUE TITLE
Define the NOMINMAX macro for Windows builds

### ISSUE THREAD

**Issue by mkoscumb** [microsoft/cpp_client_telemetry#774]
**Problem**

Windows.h for various legacy reasons `#define max(...)` and `#define min(...)`. This causes wonderfully annoying build breaks with usage of things like std::numeric_limits<T>::max(), std::min() and std::max(), or really any max or min method invocations.

**Proposed Solution**
Define the NOMINMAX macro in the Windows build scripts. This will prevent Windows.h from define'ing those macros.

**Comment by maxgolov** [comment]
I'm mostly fine with that, except there are some internal Windows SDK headers that require their own definition. This is a legacy Windows SDK quirk.... MAYBE it's okay to define it, hopefully not breaking any product that uses us. I now of one test framework that needs the Windows SDK definition... (thus, the ugly quirk in our code that was doing `#ifdef max` )

**Comment by maxgolov** [comment]
See note 3 here that explains the use-case when you need the original Windows SDK macro definition (I hit this):
http://www.suodenjoki.dk/us/archive/2010/min-max.htm
