### ISSUE TITLE
json.hpp compiler errors when compiling on MSVC

### ISSUE THREAD

**Issue by SahilAshar** [microsoft/cpp_client_telemetry#833]
When compiling `win32-lib` on MSVC, `\lib\include\mat\json.hpp` throws `warning C28020: The expression '0<=_Param_(1)&&_Param_(1)<=400-1' is not true at this call.: Lines: 14534, 14554`, which is treated as an error. 

This is a [known issue](https://github.com/nlohmann/json/pull/1969) and was fixed in [Release 3.8.0](https://github.com/nlohmann/json/releases/tag/v3.8.0) of the JSON library.

**Comment by maxgolov** [comment]
Please use `pragma` for now to disable the warning. We can consider upgrading dependency for the next release, assuming there is no push-back. It may require a few iterations for each product to register the usage of specific OSS library version.
