### ISSUE TITLE
Exception being thrown during initialization of LogManager with  HAVE_MAT_STORAGE disabled.

### ISSUE THREAD

**Issue by SahilAshar** [microsoft/cpp_client_telemetry#834]
Building `win32-lib` on VS2019 with MSVC 14.2. `sqlite` module is disabled via the `HAVE_MAT_STORAGE` flag being disabled in `config-custom.h`.

When initializing `LogManager` with `HAVE_MAT_STORAGE` disabled, an exception is thrown. It occurs at Line 89 of `OfflineStorageHandler.cpp`.
```
Exception thrown: read access violation. 
std::shared_ptr<Microsoft::Applications::Events::IOfflineStorage>::operator->**<Microsoft::Applications::Events::IOfflineStorage,0>**(...) returned nullptr.
```

I'm pretty sure this is happening because of `OfflineStorageFactory::Create()` in `OfflineStorageFactory.cpp`. If MAT Storage is disabled, it returns `nullptr` (Lines 39-40 of `OfflineStorageFactory.cpp`).  

Is this was intended behavior? Or am I doing something incorrectly in my initialization to cause this exception?

**Comment by maxgolov** [comment]
Most likely it's a recent regression. There is presently no CI loop to validate that build combo. This is not very frequently used build combo... Thus, highly likely got regressed without being noticed. Need to fix it.

**Comment by maxgolov** [comment]
I sent the fix for review. Please take a look.
