### ISSUE TITLE
[Android] Mismatch between VALUE_EALREADY and EALREADY when calling flushAndTeardown

### ISSUE THREAD

**Issue by robertwernsman** [microsoft/cpp_client_telemetry#863]
**Describe your environment.** 
Android build version: 11
Android API level: 30
1DS SDK version: EVT-Android-C++-No-3.5.67.1
Build machine details: 
```
Operating System: Pop!_OS 20.04 LTS
ID_LIKE="ubuntu debian"
Kernel: Linux 5.8.0-7625-generic
Architecture: x86-64
```

**Steps to reproduce.**
Once my app is done with telemetry data collection, I call flushAndTeardown() before exiting my Runnable that is executing the telemetry code. On some occasions, I get an exception during this method call. Unsure how to consistently repro, but I have reported hits in selfhost population.

**What is the expected behavior?**
The exit status should not return an unsupported value.

**What is the actual behavior?**
`java.lang.IllegalArgumentException: Unsupported value: 114
at com.microsoft.applications.events.Status.getEnum(Status.java:64)
at com.microsoft.applications.events.LogManager.flushAndTeardown(LogManager.java:447)
at`

**Additional context.**
I notice that [line 72 in Status.java](https://github.com/microsoft/cpp_client_telemetry/blob/a9ac12166c917c32dccaf230624b69df654780b8/lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/Status.java#L72) defines VALUE_EALREADY = 103. However, on my system that built the 1DS SDK, this value is different. On [line 36 of Enums.hpp](https://github.com/microsoft/cpp_client_telemetry/blob/a924650883ecfd44f12dba131ca117f502f372b9/lib/include/public/Enums.hpp#L36), it refers to the value defined in the errno.h. I believe the errno.h file on my system that it is resolving to defines it as the following: 

`#define	EALREADY	114	/* Operation already in progress */
`

So it seems like the native layer is trying to report EALREADY, but this is being interpreted by the Java layer as an unsupported value. **_Is this a build/setup issue on my end, or an issue within 1DS codebase? Please let me know if there is a way I can mitigate this._**

**Comment by maxgolov** [comment]
@larvacea - can we adjust the Java layer to match the native definition, since the present implementation is technically available only for Android (Linux) ?

Okay, this one is interesting:
- `103` - is the value of this constant on Windows.
- `114` - is the value of this constant on (most) Linux / Android.

Maybe we should just totally use our own custom value for that, to normalize this between different OS.

**Comment by robertwernsman** [comment]
Thanks for the followup. In the meantime, our strategy is to catch this IllegalArgumentException when we call flushAndTeardown() and silently log it to Log.e. If the status is truly trying to reflect "Operation already in progress", then we are assuming our app has nothing further it needs to do for teardown.

@maxgolov Do you know of any repercussions this error could be causing with regards to eventing/uploading? Its been reported in our selfhost several times, so we wanted to know whether it could be causing/indicating an issue with getting events from a device.

**Comment by maxgolov** [comment]
Technically the second `FlushAndTeardown` in C++ is rather benign: it triggers an error, but nothing bad happens. I think we should treat it the same way in Java layer. Most likely somehow you might be calling the same teardown sequence twice (just a speculation). There shouldn't be really any impact, catching it seems like the right thing to do for now.
