### ISSUE TITLE
InformatonProviderImpl::UnRegisterInformationChangedCallback doesn't unregister the first callback

### ISSUE THREAD

**Issue by mschofie** [microsoft/cpp_client_telemetry#880]
**Describe your environment.**
We're seeing crashes on Windows Store applications receiving power-state change notifications. The crash is in [InformationProviderImpl::OnChanged](https://github.com/microsoft/cpp_client_telemetry/blob/d2dd0e378a14286c5c4a1ad4778881821739e611/lib/pal/InformationProviderImpl.cpp#L56), specifically:

```c++
size_t count = local_callbacks.size();
for (size_t index = 0; index < count; ++index)
{
    IPropertyChangedCallback* cur_callback = local_callbacks[index];
    if (cur_callback != NULL)
    {
        cur_callback->OnChanged(propertyName, propertyValue);
    }
}
```

The `local_callbacks` contains an entry that is not valid, so our application crashes on `cur_callback->OnChanged(propertyName, propertyValue);`.

The bug appears to be in `InformatonProviderImpl::UnRegisterInformationChangedCallback`, the `index > 0` check looks like it should be `index >= 0`:

```c++
    void InformatonProviderImpl::UnRegisterInformationChangedCallback(int callbackToken)
    {
        size_t index = (size_t)(callbackToken - 1);

        std::lock_guard<std::mutex> lock(m_lock);
        size_t count = m_callbacks.size();
        if (index > 0 && index < count)
        {
            // Don't ever delete the item from the vector.
            // Just set it to NULL.
            m_callbacks[index] = NULL;
            --m_registeredCount;
        }
    }
```

Since the `m_callbacks` is indexed with a 0-base, then `0` is a valid entry - it's the first entry. 

**Steps to reproduce.**
1. Initialize a LogManager that uses an IInformationProvider implementation
2. `LogManager::FlushAndTeardown` the LogManager.
3. Cause a power-state change notification.

**What is the expected behavior?**
No crash.

**What is the actual behavior?**
Crash in `InformationProviderImpl::OnChanged`.

**Additional context.**
I've written unit tests for `InformatonProviderImpl` that cover this scenario and reproduce the problem, and have a fix that fixes the unit tests.

**Comment by maxgolov** [comment]
@mschofie - can you contribute a PR with the fix?

**Comment by mschofie** [comment]
Yes... I'm trying to follow [the instructions](https://github.com/microsoft/cpp_client_telemetry_modules/blob/master/CONTRIBUTING.md#pull-request) for a PR, but I'm getting 403's when pushing... I think I need to check permissions...?

**Comment by mschofie** [comment]
Oh, I think I need to be a Collaborator. And I don't meet the requirements. How can I share a fix for a Collaborator to merge?

**Comment by maxgolov** [comment]
@mschofie - yes, I sent you the instructions. We'd add you to group and you'd be able to create a branch and send in a PR.
