### ISSUE TITLE
Ability to stop collection of user analytics / SDK UUID.

### ISSUE THREAD

**Issue by lulululululu** [microsoft/cpp_client_telemetry#891]
Before opening a feature request against this repo, consider whether the feature is generic enough for the SDK, or it should be a specific plugin/extension to the SDK.

**Is your feature request related to a problem?**
There is no way to disable collecting SDK UID using the SDK. 

**Describe the solution you'd like.**
Add ability to disable collecting OS version. Ideally, add a method `semanticContext->SetSDKUID()` which can take `null`, empty string, "redacted" or take an option to turn it off.

**Describe alternatives you've considered.**

**Additional context.**

**Comment by maxgolov** [comment]
As discussed, please use custom decorator to clear the field.

**Comment by lalitb** [comment]
Closing as no response. Please reopen if still required,
