### ISSUE TITLE
Build issue in examples

### ISSUE THREAD

**Issue by iaiaecyx** [microsoft/cpp_client_telemetry#919]
I am trying to build EventSender, SampleCpp and SampleCppLogManager, but they have below build issue:
![image](https://user-images.githubusercontent.com/89370957/130565733-5ddba44a-f389-4d99-b46e-e5347af95c8e.png)
Do you have any idea about how to resolve this issue?

**Comment by maxgolov** [comment]
I believe we sorted out the issue offline on Teams: dependencies must be built manually; for static flavor the necessary libs (e.g. `wininet`) must be added to the list of target libraries. Feel free to reopen if this is not the case.
