### ISSUE TITLE
Do we fire "applifecycle" internally from OneDS SDK ?

### ISSUE THREAD

**Issue by nishchith-cp** [microsoft/cpp_client_telemetry#939]
We have "applifecycle" table in kusto database. 

OneDS SDK has the below API to log "applifecycle" events.  
```
-(void) logAppLifecycleWithState:(enum ACTAppLifecycleState)state
                 eventProperties:(nullable ACTEventProperties*)properties;

```
But in Teams source code, we don't see this API being called anywhere. 
Is there a chance `applifecycle` events are fired from within the oneDS library?

**Comment by lalitb** [comment]
@nishchith-cp - As SDK isn't logging app lifecycle events on itself, do you think this issue still belongs here or needs more debugging from the Aria side ?

**Comment by nishchith-cp** [comment]
I will check from our end as well. Thank you for all the support
