### ISSUE TITLE
Android add device class information

### ISSUE THREAD

**Issue by BiliBoomBo** [microsoft/cpp_client_telemetry#946]
I'm from Edge Mobile Team.
We are trying to get some device class information (such as “Android.Phone” / “Android.PC”), but it seems no collected by Edge Data Pipeline. 
We are told that adding those information need to be done in OneDS, but we don’t know the right process.
Could your team provide any help? Many thanks~

**Comment by lalitb** [comment]
@BiliBoomBo - The PR needs to be raised to add the support.
Please refer to the PR for adding device class information for iOS:
https://github.com/microsoft/cpp_client_telemetry/pull/945/
Changes would be required here: https://github.com/microsoft/cpp_client_telemetry/blob/main/lib/pal/posix/DeviceInformationImpl_Android.cpp

Tagging @larvacea  @saurabh-sagrawal if they want to add more information here.

**Comment by BiliBoomBo** [comment]
Thanks @lalitb !
I have created a PR on this issue and ask your team to review it. 
https://github.com/microsoft/cpp_client_telemetry/pull/951

**Comment by lalitb** [comment]
#951 fixes this.
