### ISSUE TITLE
potential bug when parse .ses files

### ISSUE THREAD

**Issue by yulin-li** [microsoft/cpp_client_telemetry#953]
**Describe your environment.** Describe any aspect of your environment relevant to the problem, including your SDK version, platform, OS version, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main brach.

**Steps to reproduce.**
I am testing this SDK on Linux and found the SDKUid changes every time I restart my app.
I think I found the reason after debugging for a while.

In `LogSessionDataProvider.cpp` L117. The SDK try to parse the content from a .ses file, and it has
```c++
StringUtils::SplitString(content, '\n', v);
if (v.size() != 2) {
   return false;
}
```

But the ses file is written by 
```c++
void LogSessionDataProvider::writeFileContents(
        const std::string &path,
        uint64_t sessionFirstTimeLaunch,
        const std::string &sessionSDKUid)
    {
        std::string contents;
        contents += toString(sessionFirstTimeLaunch);
        contents += '\n';
        contents += sessionSDKUid;
        contents += '\n';
```

So the content should be `xx\nxx\n`, then the `StringUtils::SplitString` will split it to 3 (`{"xx", "xx", ""}` (empty string at end)
And then the check `v.size() == 2` always failed. Therefore, .ses file always parsed failed and create a new session id every run.

**What is the expected behavior?**
What did you expect to see?

**What is the actual behavior?**
What did you see instead?

**Additional context.**

**Comment by lalitb** [comment]
> Therefore, .ses file always parsed failed and create a new session id every run.

Agree, this looks to be issue and will create `ses` file with the new `SDKUid` with every restart.

**Comment by lalitb** [comment]
#957 fixes this
