### ISSUE TITLE
How to override the DeviceInfo_Id field that 1DS SDK automatically adds to events?

### ISSUE THREAD

**Issue by MehranAzimi-msft** [microsoft/cpp_client_telemetry#954]
Hi 1DS community, I am integrating 1DS SDK into iOS SDK/App. I am logging a simple test event like this: 
```
auto logger = LogManager::GetLogger();
if (logger)
{
    EventProperties event;
    event.SetName("MyTestEvent");
    event.SetProperty(COMMONFIELDS_EVENT_PRIVTAGS, PDT_ProductAndServicePerformance);
    event.SetProperty("Some property", "Some value");
    logger->LogEvent(event);
}
```

I noted that a DeviceInfo_Id field is automatically added to my event, and it is set to a GUID that identifies the device. For privacy reasons, I need no device identifier logged from our code, and I was wondering how I can I override this field. I've tried  
` event.SetProperty(COMMONFIELDS_DEVICE_ID, "");`
but still the deviceId is showing up in the logged events. Is there an API or specific privacy settings I can use to override this field?

Thanks

**Comment by lalitb** [comment]
I think obj-c binding for iOS does auto-populate the device_id field, did you try resetting it using `ODWSemanticContext ::SetDeviceId()` 

https://github.com/microsoft/cpp_client_telemetry/blob/63a5d2a2505697cebebf37aaadb7b2292015bf59/wrappers/obj-c/ODWSemanticContext.h#L54

@eduardo-camacho , @kindbe can provide you with more information here.

**Comment by eduardo-camacho** [comment]
Yes, using semantic context is the way to override it

**Comment by MehranAzimi-msft** [comment]
using semantic context worked for me as suggested. Thanks for your help.
