### ISSUE TITLE
Potential data race in InformationProviderImpl?

### ISSUE THREAD

**Issue by PetrGuan** [microsoft/cpp_client_telemetry#974]
**Describe your environment.** Describe any aspect of your environment relevant to the problem, including your SDK version, platform, OS version, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main brach.

Outlook iOS, 'OneDsCppSdk.iOS', '3.5.117.1'

**Steps to reproduce.**
Describe exactly how to reproduce the error. Include a code sample if applicable.

**What is the expected behavior?**
No data race.

**What is the actual behavior?**
Xcode warning for data race.

**Additional context.**

Not sure if it's a false positive. 

![Screen Shot 2021-12-07 at 5 12 46 PM](https://user-images.githubusercontent.com/7663073/145000495-9a946a19-487c-4b60-b869-c6b21cc17629.png)

```
void InformatonProviderImpl::OnChanged(std::string const& propertyName, std::string const& propertyValue)
    {
        try {
            std::lock_guard<std::mutex> lock(m_lock); // this will fix?
            if (m_registeredCount > 0)
            {
                std::vector<IPropertyChangedCallback*> local_callbacks;
                {
                    local_callbacks.insert(local_callbacks.end(), m_callbacks.begin(), m_callbacks.end());
                }

                ...
            }
        }
    }
```

**Comment by PetrGuan** [comment]
I'm a developer from Microsoft Outlook iOS, but it seems I received 403 while trying to `push branch` to this repo.

**Comment by lalitb** [comment]
@PetrGuan  - See if you access to contribute following this [link](https://microsoft.sharepoint.com/teams/1ds.sdk.cpp/SitePages/Home.aspx?xsdata=MDN8MDF8fDNjODU0OTgyYjVjMDRiMjZiMDhjN2U5MjAwOWViMzY4fDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDF8MHw2Mzc3MzgyODc0MjE4MTI3NjR8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaUlpd2lRVTRpT2lJaUxDSlhWQ0k2TVRKOQ%3D%3D&sdata=ZWhZVzRxdW9XK2lOUHJIMExrbWFpL2x1bUk4ai9RbkFLaFN4SWtxRktpMD0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Clabhas%40microsoft.com&OR=Teams-HL&CT=1638855104964)

-clip
Want to contribute?

- please create Microsoft Organization GH account here: https://opensource.microsoft.com/
- then join our project https://repos.opensource.microsoft.com/microsoft/teams/client-telemetry-sdk/join/ , which will give you contributors rights. BTW, we LOVE community contributions!
- once you got the contributor access, please read this private page that details how to contribute:
https://github.com/microsoft/cpp_client_telemetry_modules/blob/master/CONTRIBUTING.md
​​​​​​​Note: the most common mistake is accessing this page without logging in using your Microsoft GH credentials. If you do not log in using your Microsoft GH credentials, then you would see 404 - Page not found . Step back and make sure you created your GH account and logged in!

--clap

**Comment by PetrGuan** [comment]
I'll try to contribute, thanks!
