### ISSUE TITLE
Win32-dll Project Build Broken

### ISSUE THREAD

**Issue by natalieparry** [microsoft/cpp_client_telemetry#979]
In the most recent version of the project, the import library (.lib file) is not generated when the rest of the Win32-dll project is built. This is a regression from previous versions (I know that commit 8781d6a898b6c62edece810eb7dcf115d29111ed builds the dll and lib correctly but have not looked into exactly when this was broken).

**Comment by lalitb** [comment]
I just built the win32-dll project on VS2019 and can see both ClientTelemetry.dll and ClientTelemetry.dll getting generated. This is on the latest version of 1DS SDK. Please help me understand the issue you are facing.

**Comment by Diego-Perez-Botero** [comment]
When I run the `build-all.cmd` script, there's no LIB in the win32-dll folder:
![image](https://user-images.githubusercontent.com/12803275/146470122-8ea89dda-55f6-41ad-af83-e9977236c83e.png)

**Comment by lalitb** [comment]
Ok, the behavior was changed as part of this PR: https://github.com/microsoft/cpp_client_telemetry/pull/852 to speed up the build process. So you have to consume the lib from the `win32-lib` folder.

**Comment by Diego-Perez-Botero** [comment]
Isn't the win32-lib output a static lib, though? Will it actually be using the DLL at all?

**Comment by lalitb** [comment]
> Isn't the win32-lib output a static lib, though? Will it actually be using the DLL at all?

win32-lib won't be using DLL. I am still trying to understand your concerns here :)

**Comment by Diego-Perez-Botero** [comment]
We want to consume this as a DLL from a C++ project, not as a static lib. This is because we want to avoid compiler incompatibility issues between the C++ project and ClientTelemetry.lib.

For us to consume this as a DLL, we expect there to be an import LIB, which contains information about how to find the functions and data, instead of the actual code. That's what's missing.

**Comment by Diego-Perez-Botero** [comment]
I know that C# projects are able to reference DLLs directly, but consuming this as a DLL from C++ requires a corresponding LIB that is different to the standalone static lib.

**Comment by lalitb** [comment]
> For us to consume this as a DLL, we expect there to be an import LIB, which contains information about how to find the functions and data, instead of the actual code. That's what's missing.

Ok, thanks for clarifying. Coming from the different world of shared-library in Linux/MacOS platform didn't realize DLLs are special and need import lib along with them. Also looks like this [PR](https://github.com/microsoft/cpp_client_telemetry/pull/889) is actually breaking this.

**Comment by Diego-Perez-Botero** [comment]
Seems like #852 should be reverted? Before those changes, you'll notice that the ClientTelemetry.lib from the win32-dll folder was smaller than that from the win32-lib, as expected.

**Comment by lalitb** [comment]
> Seems like #852 should be reverted? Before those changes, you'll notice that the ClientTelemetry.lib from the win32-dll folder was smaller than that from the win32-lib, as expected.

Yes, I did notice the size difference while testing too. Would you like to raise the PR for the fix?  Else, I can do it sometime next week with some more testing.

**Comment by Diego-Perez-Botero** [comment]
Thanks for the quick replies and initial assessment, @lalitb . I'm running low on cycles, but maybe @natalieparry can raise the PR with the fix.

**Comment by natalieparry** [comment]
I'm happy to make the change, but I'm being denied access to the project when I try to push. I am a member of the Microsoft organization in GitHub and can't find any other reason in the contribution docs why this could be happening.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/96266825/146805268-0e336159-b03c-45a6-9f83-f33db39a3428.png">

**Comment by lalitb** [comment]
@natalieparry - IF you already have Microsoft GH account, you and join the project here - https://repos.opensource.microsoft.com/orgs/microsoft/teams/client-telemetry-sdk/join/ . Once approved, you should have required access.

**Comment by natalieparry** [comment]
Just submitted PR #980 for review. Thanks for guidance on the OS rules.
