### ISSUE TITLE
Is it a data race in Statistics:: scheduleSend()?

### ISSUE THREAD

**Issue by PetrGuan** [microsoft/cpp_client_telemetry#984]
Outlook Mobile iOS, 'OneDsCppSdk.iOS', '3.5.321'.

I'm not sure if it's a false alarm by Thread Sanitizer. See the screenshot below. I've checked the codes and it seems that the `m_intervalMs` is not thread safe, is it on purpose?

![Screen Shot 2022-01-10 at 1 41 17 PM](https://user-images.githubusercontent.com/7663073/148722874-693f172d-c17e-4383-ab68-b091111f0a1b.png)

**Comment by PetrGuan** [comment]
Hum... I'll probably raise a PR myself.

**Comment by lalitb** [comment]
@PetrGuan - Sorry for late reply. Feel free to raise a fix for the issue. We can discuss this over the PR.

**Comment by PetrGuan** [comment]
Thanks! I'll close this and raise a PR later
