### ISSUE TITLE
Missing DisableAdvancedScans attributes in nativeInitializePrivacyGuard()

### ISSUE THREAD

**Issue by abbytran1996** [microsoft/cpp_client_telemetry#988]
I saw that the function [nativeInitializePrivacyGuard()](https://github.com/microsoft/cpp_client_telemetry/blob/c18ed6c034f9abc748e266f781a1a2481cfc32fc/lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/PrivacyGuard.java#L10) doesn't have the boolean `DisableAdvancedScans`, whereas this jni function [here](https://github.com/microsoft/cpp_client_telemetry/blob/c18ed6c034f9abc748e266f781a1a2481cfc32fc/lib/jni/PrivacyGuard_jni.cpp#L86) has that attribute. 

Is it intentional? 

Android recent ran into [this JNI error at booting](https://github.com/microsoft/cpp_client_telemetry/issues/989) and I'm not sure if they are related or not.

**Comment by kivarsha** [comment]
@sid-dahiya This might have broken it: [!958](https://github.com/microsoft/cpp_client_telemetry/pull/958)
