### ISSUE TITLE
Loggers with different collector URLs at a time, +(nullable ODWLogger *)loggerWithTenant:(NSString *)tenantToken source:(NSString *)source withConfig:(nonnull ODWLogConfiguration *)config;

### ISSUE THREAD

**Issue by nishchith-cp** [microsoft/cpp_client_telemetry#991]
**- Describe your environment:** 
iOS
pod 'OneDsCppSdk.iOS', '3.5.200'

**Scenario:**
Want to use the below API to create a new logger with a different configuration. But the API does not allow sending the following dictionary configuration of PG as part of the parameter. Is there any other way to set the dictionary configuration for the API?

```
**Config that needs to be sent:**
    // For privacy guard, set CFG_MAP_COMPAT's CFG_STR_COMPAT_PREFIX to "" to set our custom baseType for events.
    NSDictionary *compatLogConfig = @{TSOneDSConfigurationKey.cfgStrCompatPrefix: @""};
    [logConfiguration setValue:compatLogConfig forKey:TSOneDSConfigurationKey.cfgMapCompat];

**API:**
/*!
 @brief Retrieves a new instance of ODWLogger for logging telemetry events. This function expects that the telemetry logging system has already been initialized.
 @param tenantToken A string that contains the tenant token.
 @param source A string that contains the name of the source of events.
 @param config A Dictionary that contains a custom configuration.
 @return An ODWLogger pointer that points to the logger for the specified tenantToken and source.
 */
+(nullable ODWLogger *)loggerWithTenant:(NSString *)tenantToken
                  source:(NSString *)source
                  withConfig:(nonnull ODWLogConfiguration *)config;

```

**Comment by nishchith-cp** [comment]
Discussed offline with @sid-dahiya 

1. The configuration for PG base type can be passed as an empty string for the TSOneDSConfigurationKey.cfgMapCompat instead of a dictionary.
2. Call `oneDsLogger?.initializePrivacyGuard(with: pgInitConfig)` if needed for logger created using different LogManager. 

3. Call this API to get a logger for a different config only if the config is different. 
```
+(nullable ODWLogger *)loggerWithTenant:(NSString *)tenantToken
                  source:(NSString *)source
                  withConfig:(nonnull ODWLogConfiguration *)config
```

**Comment by nishchith-cp** [comment]
Need some more clarifications for the above API.

1. Test accounts to test the end to end behavior of the below API to get the logger for different config
```
+(nullable ODWLogger *)loggerWithTenant:(NSString *)tenantToken
                  source:(NSString *)source
                  withConfig:(nonnull ODWLogConfiguration *)config
```
2. If we create multiple loggers using the above API would it lead to performance issues since we create new LogManagers in the OneDS SDK classes
https://github.com/microsoft/cpp_client_telemetry/blob/a8c90ab03a4667d4e3a16ef15bbe37b355914728/wrappers/obj-c/ODWLogManager.mm

We would need to support multiple loggers with the same configuration for different tenant tokens, which will result in calling this API multiple times.

**Comment by eduardo-camacho** [comment]
@nishchith-cp, for using distinct tenant tokens you don't need to have different configurations, just use loggerWithTenant:(nonnull NSString *)tenantToken  which won't create multiple LogManager's .

In case you need to keep several loggers with different configuration each, it will require to internally have multiple LogManagers, since each LogManager can support a single configuration. In order to have loggers with different configuration you need to:
1. Call loggerWithTenant, to get have internal LogManager initialized with default configuration (or with a Dictionary with configuration settings you specify)
2. Call [ODWLogConfiguration getLogConfigurationCopy], then use it to call loggerWithTenant:(nonnull NSString *)tenantToken
                  source:(nonnull NSString *)source withConfig:(nonnull ODWLogConfiguration *)config

**Comment by nishchith-cp** [comment]
Thank you @eduardo-camacho for all the details: 

Currently, I am trying the below flow to use the API that you suggested.

1. For the first time creation of the logger. We call the `ODWLogManager` method
`+(nullable ODWLogger *)initForTenant:(nonnull NSString *)tenantToken withConfig:(nullable NSDictionary *)config;`
2. To get any loggers with the different tenant tokens where the configuration would be the same. We used the `ODWLogManager` method
`+(nullable ODWLogger *)loggerWithTenant:(NSString *)tenantToken`
3. To create a logger with different configurations, mainly we need loggers with different `eventCollectorUri`:
- Make sure to call Step1 before so that the LogManager is initialised
- Get an `ODWLogConfiguration` copy and set the `eventCollectorUri` along with any other configuration as below. 
Would this work if I set the `eventCollectorUri` this way?  
```
    private func createOneDSLogConfiguration(_ configuration: [String: String]) -> ODWLogConfiguration {
        let odwConfiguration = ODWLogConfiguration.getCopy() ?? ODWLogConfiguration()
        for (key, value) in configuration {
            odwConfiguration.set(key, withValue: value)
        }
        return odwConfiguration
    }
```

4. Can we use `loggerWithTenant:(nonnull NSString *)tenantToken
source:(nonnull NSString *)source withConfig:(nonnull ODWLogConfiguration *)config` API instead of the step2 API always even if there is no configuration change? 

5. Would all the APIs supported by the ODWLogManager apply to the loggers created by the above API?
Eg:
```
+(void)setTransmissionProfile:(ODWTransmissionProfile)profile;
+(void)pauseTransmission;
+(void)resumeTransmission;
+(ODWStatus)flushAndTeardown;
```

**Comment by lalitb** [comment]
> (5) I guess so, but since you are allowcating multiple LogManager objects I would defer that question to @lalitb

Yes it would be supported.

**Comment by nishchith-cp** [comment]
@eduardo-camacho @lalitb 
In swift when I try to use `getLogConfigurationCopy` an error shows up to use `getCopy` instead. PFA
<img width="1061" alt="Screenshot 2022-02-24 at 9 52 38 AM" src="https://user-images.githubusercontent.com/85876413/155587972-fadf9805-1856-4088-be5e-58df44aa32e5.png">

I tested by creating multiple loggers with CollectorURL1 and one logger with a different CollectorURL2.
The LogManager was initialized with the CollectorURL1. I used the API `loggerWithTenant:(nonnull NSString *)tenantToken source:(nonnull NSString *)source withConfig:(nonnull ODWLogConfiguration *)config` to create other loggers with CollectorURL1 and CollectorURL2.

When I used the network inspector to see if both the collector URLs are being used. I could see that only the CollectorURL1 that was used to initialise the LogManager is displayed but not the CollectorURL2. Is there any other way I can verify if the collector URLs are correctly used to log the events?
<img width="1169" alt="Screenshot 2022-02-25 at 12 13 53 AM" src="https://user-images.githubusercontent.com/85876413/155588596-36411aea-6eb3-41b9-8f9e-fb173e3e75c5.png">

**Comment by lalitb** [comment]
@nishchith-cp   CollectorURL configured for each LogManager, and all loggers created for a particular LogManager use that configured collector URL. Is this not the behavior you are observing?

**Comment by nishchith-cp** [comment]
@lalitb 
When I check the network traces while logging the events using loggers created with different collector URLs, I just see one collector URL in the network trace. I should be seeing both right?  Is there any other way I can verify this?

**Comment by lalitb** [comment]
You should ideally see both the URL through network trace ( intercepting network traffic using fiddler / Charles proxy ). Are you seeing the default collector URL `https://self.events.data.microsoft.com/OneCollector/1.0/` for all the loggers, or only the URL configured through first/last call to `loggerWithTenant`?

**Comment by nishchith-cp** [comment]
@lalitb 
Tried with the latest version as well - 3.5.321. I see that the "eventCollectorUri" is not updated in the LogManager associated with the logger created with a different configuration. 

<img width="1624" alt="Screenshot 2022-03-01 at 8 14 02 PM" src="https://user-images.githubusercontent.com/85876413/156192542-b36bdcfb-adec-4d88-9462-c7c17ab4ffb5.png">

**Comment by lalitb** [comment]
@nishchith-cp - As indicated in my previous comment, can you ensure setting the parameters mentioned there. Specifically config["name"] and config["config"]["host"]. I have tested the 1ds cpp core api, and it does support separate collector endpoints for logManagers.
I am not an object-c expert and also don't have the hardware to test it, but looking into the ios wrapper code in the 1ds repo, it looks good to me.

**Comment by eduardo-camacho** [comment]
@nishchith-cp, please share a snipped of your code, since initialization to events logging, so we can take a look.

**Comment by nishchith-cp** [comment]
@lalitb Below is the code that we are using to call the API. What should be the values associated with "host" and "name"? Let me try this as well.

```
 - (id<TSTelemetryLoggerProtocol>) loggerForTenant:(NSString*)tenantID config:(NSDictionary*)config
{
    id<TSTelemetryLoggerProtocol> logger = nil;
    
    if (![self.telemetryLogManager isInitialised])
    {
        logger = [self.telemetryLogManager initForTenant:tenantID source:@""];
	// In turn calls the SDK API “ODWLogManager: +(nullable ODWLogger *)initForTenant:(nonnull NSString *)tenantToken”
    }
    else
    {
   		NSMutableDictionary *logConfiguration = NSMutableDictionary.new;
        collectorUrl = @"https://tb.events.data.microsoft.com/OneCollector/1.0/";
        [logConfiguration setValue:collectorUrl forKey: @“eventCollectorUri”];
        logger = [self.telemetryLogManager loggerForTenant:tenantID configuration:logConfiguration];
	// In turn calls the SDK API “ODWLogManager: +(nullable ODWLogger *)loggerWithTenant:(nonnull NSString *)tenantToken source:(nonnull NSString *)source withConfig:(nonnull ODWLogConfiguration *)config
    }
    
    return logger;
}

```

**Comment by nishchith-cp** [comment]
@lalitb By setting the host for the configuration, I am able to see both the collector URLs in the network trace. Thank you so much for all the support. Really appreciate it. 
Just one last thing. I am setting the host the same as the collector URL. This should be ok, right?

```
        let odwConfiguration = ODWLogConfiguration.getCopy() ?? ODWLogConfiguration()
        var collectorURL = "https://tb.events.data.microsoft.com/OneCollector/1.0/"
        odwConfiguration.set("eventCollectorUri", withValue: collectorURL)
        odwConfiguration.setHost(collectorURL)

```

**Comment by lalitb** [comment]
> Just one last thing. I am setting the host the same as the collector URL. This should be ok, right?

Yes, it should be fine. Glad it worked.

**Comment by eduardo-camacho** [comment]
@nishchith-cp, please make sure you get a new copy of log configuration for collectorURI-3 before creating a new logger, likely you are reusing object

**Comment by nishchith-cp** [comment]
@eduardo-camacho I am always creating a copy of ODWLogConfiguration

This is what I am doing
```
    func initFor(tenant: String, configuration: [String: Any]) -> TSTelemetryLoggerProtocol {
        if let collectorUri = configuration[TSOneDSConfigurationKey.eventCollectorUri] as? String {
            /// Keep track of the collector uri that is used to initialise the LogManager.
            defaultCollectorUri = collectorUri
        }
        print("Nishchith: Initialised: \(defaultCollectorUri) [] \(self) [] \(tenant)")
        let oneDSLogger = ODWLogManager.initForTenant(tenant, withConfig: configuration)
        return TSOneDSLogger(oneDsLogger: oneDSLogger, logService: logService)
    }
    
    func logger(for tenant: String, source: String) -> TSTelemetryLoggerProtocol {
        let oneDSLogger = ODWLogManager.logger(withTenant: tenant, source: source)
        return TSOneDSLogger(oneDsLogger: oneDSLogger, logService: logService)
    }
    
    func logger(for tenant: String, configuration: [String: String]) -> TSTelemetryLoggerProtocol? {
        if let odwConfiguration = createOneDSLogConfiguration(configuration) {
            /// Get logger with different configuration
            guard let odwLogger = ODWLogManager.logger(withTenant: tenant, source: "", withConfig: odwConfiguration) else {
                assertionFailure("Failed to create logger with different configuration. LogManager should be initialised before making this call.")
                return nil
            }
            print("Nishchith: LoggerWithDifferentConfig: \(configuration[TSOneDSConfigurationKey.eventCollectorUri] ?? "") [] \(self) [] \(tenant)")
            return TSOneDSLogger(oneDsLogger: odwLogger, logService: logService)
        }
        print("Nishchith: LoggerWithTenant: \(defaultCollectorUri ?? "") [] \(self) [] \(tenant)")
        /// If the collector uri is not different fallback to getting the logger with default initialised configuration
        return logger(for: tenant, source: "")
    }

    private func createOneDSLogConfiguration(_ configuration: [String: String]) -> ODWLogConfiguration? {
        /// If configuration has different collector uri from the collector uri that was used to initialise the log manager create a new ODWConfiguration
        if let collectorUri = configuration[TSOneDSConfigurationKey.eventCollectorUri] as? String,
           let defaultCollectorUri = defaultCollectorUri,
           !(defaultCollectorUri.lowercased().contains(collectorUri.lowercased()) || collectorUri.lowercased().contains(defaultCollectorUri.lowercased())) {
            let odwConfiguration = ODWLogConfiguration.getCopy() ?? ODWLogConfiguration()
            /// Host has to be set. Else the API doesnt work nad uses the initialised collector uri by default
            odwConfiguration.setHost(collectorUri)
            for (key, value) in configuration {
                odwConfiguration.set(key, withValue: value)
            }
            return odwConfiguration
            
        }
        return nil
    }

```

```
Nishchith: Initialised: Optional("https://tb.events.data.microsoft.com/OneCollector/1.0/") [] xxxxxxxx-527d75d3b928-7064

Nishchith: LoggerWithTenant: https://tb.events.data.microsoft.com/OneCollector/1.0/  [] xxxxxxxx-ea7753fb9887-7371

Nishchith: LoggerWithDifferentConfig: https://pf.events.data.microsoft.com/OneCollector/1.0/ [] xxxxxxxx-10a35dfc3f11-7584

Nishchith: LoggerWithTenant: https://tb.events.data.microsoft.com/OneCollector/1.0/ [] xxxxxxxx-ea7753fb9887-7371
Nishchith: LoggerWithTenant: https://tb.events.data.microsoft.com/OneCollector/1.0/ [] xxxxxxxx-527d75d3b928-7064
Nishchith: LoggerWithTenant: https://tb.events.data.microsoft.com/OneCollector/1.0/ [] xxxxxxxx-ea7753fb9887-7371

Nishchith: LoggerWithDifferentConfig: https://eu-teams.events.data.microsoft.com/OneCollector/1.0 [] xxxxxxxx-527d75d3b928-7064
Nishchith: LoggerWithDifferentConfig: https://eu-teams.events.data.microsoft.com/OneCollector/1.0 [] xxxxxxxx-ea7753fb9887-7371

Nishchith: LoggerWithTenant: https://tb.events.data.microsoft.com/OneCollector/1.0/ [] xxxxxxxx-f0b25b00a080-7662
Nishchith: LoggerWithTenant: https://tb.events.data.microsoft.com/OneCollector/1.0/ [] xxxxxxxx-e3d0a702f932-7448

```

Charles proxy screen shot. The "TFL55" shoudl go as part of "pf.events.data.microsoft.com"
<img width="463" alt="Screenshot 2022-03-07 at 11 43 08 AM" src="https://user-images.githubusercontent.com/85876413/156978135-fd7ea6bf-e669-4ee4-8ef9-c8c245e61e23.png">

**Comment by lalitb** [comment]
@nishchith-cp - Where are you setting the `config["name"]` and `config["config"]["host"]` above ?

**Comment by nishchith-cp** [comment]
@lalitb `setHost:` internally adds the details as this `config["config"]["host"]`
 `odwConfiguration.setHost(collectorUri)`

I even tried `config["name"]` by setting it to collectorUri passed. Same result as above.

**Comment by eduardo-camacho** [comment]
1DS Obj-C wrapper has two usage scenarios: 
1)Creating and using one or more loggers using a single configuration
2)Creating and using multiple loggers, where each one of these logger might use some non-default configuration. This is your scenario

Consumers on scenario (2) would first call initForTenant:tenantToken to get inner SDK infra setup (and possibly use returned logger with default configuration if needed), and then, for each new configuration you need to: call ODWLogConfiguration getLogConfigurationCopy, change config values to need on that copy and finally call ODWLogManager loggerWithTenant:TenantToken:source:withConfig. I could not find loggerForConfig you mentioned.

Regarding your point (1), we can't drop or make changes to existing API's signature because we would break backward compatibility with existing consumers. We could only add new signatures, but we need to be careful to not introduce slight variations that could confuse consumers. Exposing ODWLogManager objects would not only confuse existing consumers, or cause us to refactor signatures and break backward compatibility. Recommendation is clients to keep track of their logger instances, rather than SDK.

Lalit made a local modification to current functional test on multiple endpoints support, to identify if there were any issues like reported on your point (2). He has not identified any issue handing 3 or more configurations with distinct endpoints, but he will send a PR soon with updated test case, to illustrate usage.

**Comment by nishchith-cp** [comment]
@eduardo-camacho @lalitb PR will be helpful. Thank you.

**Comment by lalitb** [comment]
@nishchith-cp - Have raised the PR to demonstrate that the core C++ API handles multiple log managers as expected.
Regarding your issue, as @eduardo-camacho pointed out for scenario 2, can you share your code ( may repo/file link) to see how loggers are being created and whether a separate copy of configuration is used for all these loggers. The part of code pasted in this issue is not helping much to understand.

**Comment by nishchith-cp** [comment]
I am creating a separate configuration to create the logger. Func: `private func createOneDSLogConfiguration(_ configuration: [String: String]) -> ODWLogConfiguration?`

// This is the main Teams OneDSManager class that accesses the ODWLogManager APIs.
https://domoreexp.visualstudio.com/Teamspace/_git/Teamspace-iOS?path=/apps/ProjectNext/Commons/Core/Libraries/Telemetry/Sources/Telemetry/Loggers/TSOneDSTelemetryLogManager.swift&version=GBdevelop&line=33&lineEnd=59&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

Below are the main methods that are being used to create the loggers with a different configuration. We can have a call to discuss more on this.
```
      /// This keeps track of the collector uri that was used to initialise the log manager. If we need a logger with a different collector uri we need to use different API.
    private var defaultCollectorUri: String?

    func initFor(tenant: String, configuration: [String: Any]) -> TSTelemetryLoggerProtocol {
        if let collectorUri = configuration[TSOneDSConfigurationKey.eventCollectorUri] as? String {
            /// Keep track of the collector uri that is used to initialise the LogManager.
            defaultCollectorUri = collectorUri
        }
        let oneDSLogger = ODWLogManager.initForTenant(tenant, withConfig: configuration)
        return TSOneDSLogger(oneDsLogger: oneDSLogger, logService: logService)
    }
    
    func logger(for tenant: String, source: String) -> TSTelemetryLoggerProtocol {
        let oneDSLogger = ODWLogManager.logger(withTenant: tenant, source: source)
        return TSOneDSLogger(oneDsLogger: oneDSLogger, logService: logService)
    }
    
    func logger(for tenant: String, configuration: [String: String]) -> TSTelemetryLoggerProtocol? {
        if let odwConfiguration = createOneDSLogConfiguration(configuration) {
            /// Get logger with different configuration
            guard let odwLogger = ODWLogManager.logger(withTenant: tenant, source: "", withConfig: odwConfiguration) else {
                assertionFailure("Failed to create logger with different configuration. LogManager should be initialised before making this call.")
                return nil
            }
            return TSOneDSLogger(oneDsLogger: odwLogger, logService: logService)
        }
        /// If the collector uri is not different fallback to getting the logger with default initialised configuration
        return logger(for: tenant, source: "")
    }

    private func createOneDSLogConfiguration(_ configuration: [String: String]) -> ODWLogConfiguration? {
        /// If configuration has different collector uri from the collector uri that was used to initialise the log manager create a new ODWConfiguration
        if let collectorUri = configuration[TSOneDSConfigurationKey.eventCollectorUri] as? String,
           let defaultCollectorUri = defaultCollectorUri,
           !(defaultCollectorUri.lowercased().contains(collectorUri.lowercased()) || collectorUri.lowercased().contains(defaultCollectorUri.lowercased())) {
            let odwConfiguration = ODWLogConfiguration.getCopy() ?? ODWLogConfiguration()
            /// Host has to be set. Else the API doesnt work and uses the initialised collector uri by default
            odwConfiguration.setHost(collectorUri)
            for (key, value) in configuration {
                odwConfiguration.set(key, withValue: value)
            }
            return odwConfiguration
        }
        return nil
    }
}
```

Below is the calling class:
https://domoreexp.visualstudio.com/Teamspace/_git/Teamspace-iOS?path=/apps/TeamsKit/TeamsKit/Classes/AXPCommon/Instrumentation/AXPEventReporter.m&version=GBdevelop&line=148&lineEnd=180&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by lalitb** [comment]
@nishchith-cp - the code looks good to me, but would let @eduardo-camacho to comment as an ios expert :)
Also, can you confirm all the three loggers are getting created through `TSOneDSTelemetryLogManager::logger(tenant, conf)` method, do you have any logs to validate that?

**Comment by eduardo-camacho** [comment]
@nishchith-cp, I'm concerned about AXPEventReporter.m:110, which I believe is the first interaction with ODWLogManager by calling your method "isInitialised", the problem I see there is: instead of calling any of the methods that cause 1DS initialization (i.e.: loggerWithTenant) with a proper tenant token, it calls loggerForSource with an empty string as parameter. This is calling LogManager::GetLogger("") without any prior initialization nor having a tenant token, which I believe it results in an undefined behavior; I will defer to @lalitb to call out what really happens there and the consequences down the road.

**Comment by nishchith-cp** [comment]
@lalitb 
Here is the log and the Charles proxy screenshot when I used the API `ODWLogManager.logger(withTenant tenantToken: [String], source: [String], withConfig config: [ODWLogConfiguration]) -> [ODWLogger]?` to create all the 3 logs. 

The collector URI in the Charles proxy is always the latest URI that was used in the above API. 

<img width="1123" alt="Screenshot 2022-03-29 at 7 48 50 PM" src="https://user-images.githubusercontent.com/85876413/160633762-4b2fa8b4-9490-4f97-a4cf-ac807a46ecde.png">

<img width="704" alt="Screenshot 2022-03-29 at 7 48 40 PM" src="https://user-images.githubusercontent.com/85876413/160633935-e2fb056c-27d3-4cf5-80d0-cbea84116804.png">

------------------------------------------------------------------------------
@eduardo-camacho 
Is there any other API that will give us the `isInitialised` state of the  `ODWLogManager`? We want to use a custom collector URI and not the one from the OneDS SDK. The API `+(nullable ODWLogger *)loggerWithTenant:(NSString *)tenantToken source:(NSString *)source;` does not take configuration as an input. And the API `+(nullable ODWLogger *)loggerWithTenant:(NSString *)tenantToken source:(NSString *)source withConfig:(nonnull ODWLogConfiguration *)config;` expects that the telemetry logging system to be initialized as per the documentation.

**Comment by nishchith-cp** [comment]
@lalitb As discussed in the meeting. I am attaching the details of config values in the below method in the objective-c wrapper class:
<img width="770" alt="Screenshot 2022-03-30 at 4 44 39 PM" src="https://user-images.githubusercontent.com/85876413/160822422-6c0b3fb5-b992-4eee-8926-85d50b83d283.png">

[Logs_LoggersWithMultipleCollectorUri.pdf](https://github.com/microsoft/cpp_client_telemetry/files/8379944/Logs_LoggersWithMultipleCollectorUri.pdf)

Observations:
The properties for the eventCollectorUri are correctly set for LogManager created within the method and the logger that is created within this method.

Only that when I check in the Charles proxy the collector URI is always the latest for the existing loggers which are created using this API.

Could please check if the required properties are passed. Unit test would pass here but the behavior seems to be different when checked on the Charles proxy.

Could you please check this

**Comment by nishchith-cp** [comment]
@lalitb @eduardo-camacho Gentle reminder on this

**Comment by lalitb** [comment]
@nishchith-cp - Thanks for providing more details. It would be interesting to see now how you are using these different loggers to send events in code, as that is not very clear from the code. Can you instead write a small obj-c program that uses 1DS obj-c wrapper to demonstrate the issue ( no swift to obj-cc conversion, no external dependencies in the demo code other than 1DS sdk.)

   - Create three different loggers using `ODWLoggerManager::loggerWithTenant()`
   - Invoke `ODWLogger::logEvent*()` to send events using these three loggers. And share the Charles proxy screenshot.

If you are above to reproduce the issue using this test code, we can scope our debugging in the 1ds part.

As mentioned earlier, I am relying on you for most of the debugging, as don't have the hardware to test this. 

Regarding
> This is calling LogManager::GetLogger("") without any prior initialization nor having a tenant token, which I believe it results in an undefined behavior; I will defer to @lalitb to call out what really happens there and the consequences down the road.

LogManager::GetLogger would return `nullptr` if the LogManager is not already `initialized. If LogManager is already initialized, it would create a logger (even if the source is an empty string).

**Comment by nishchith-cp** [comment]
@lalitb 

PFA for the sample application and the Charles proxy screen. I see the same issue with the sample app as well. The `ODWLogManager :+(nullable ODWLogger *)loggerWithTenant:(nonnull NSString *)tenantToken source:(nonnull NSString *)source withConfig:(nonnull ODWLogConfiguration *)config` always picks the most recent collector URI for all the loggers that have been created using this API. 

In the below case: 
`"https://eu-teams.events.data.microsoft.com/OneCollector/1.0/"` is the most recent collector URI with which 3rd logger was created. The same collector URI is applied for logger2 which has a different collector URI. Hope this helps.

[OneDSSampleApp.zip](https://github.com/microsoft/cpp_client_telemetry/files/8415450/OneDSSampleApp.zip)
<img width="797" alt="Screenshot 2022-04-05 at 11 40 26 AM" src="https://user-images.githubusercontent.com/85876413/161691066-6590710f-c3f3-46fe-9991-9f29629b3270.png">

cc: @aamittal1989 @karthika-msft

**Comment by lalitb** [comment]
@nishchith-cp Thanks for the sample application. As mentioned in my previous comment, I was expecting the sample application to

- Create three different loggers using ODWLoggerManager::loggerWithTenant()
- Invoke ODWLogger::logEvent*() to send events using these three loggers. And share the Charles proxy screenshot.

While this application is creating first logger using initForTenant, and other two using loggerWithTenant. Can you instead use `loggerWithTenant` for all the loggers you want to use. You may call `initForTenant` to create unused logger if it needs to be called initially.

**Comment by nishchith-cp** [comment]
@lalitb 
It is the same behavior for all the loggers created from `ODWLogManager :+(nullable ODWLogger *)loggerWithTenant:(nonnull NSString *)tenantToken source:(nonnull NSString *)source withConfig:(nonnull ODWLogConfiguration *)config`

The sample app has:
1. An unused logger was created since we need to initialize the Log Manager before calling the above API.
2. 3 loggers created using the above config API. 

All the events are going through the collector URI of the most recent configuration used for the above config API.
PFA for the sample app and the Charles 

<img width="800" alt="Screenshot 2022-04-19 at 1 01 03 PM" src="https://user-images.githubusercontent.com/85876413/163950841-1079dfd5-b766-42d8-a54a-42f387b85fff.png">

[OneDSSampleApp 2.zip](https://github.com/microsoft/cpp_client_telemetry/files/8510884/OneDSSampleApp.2.zip)

cc: @aamittal1989 , @karthika-msft

**Comment by nishchith-cp** [comment]
@lalitb, @eduardo-camacho 
Was there any fix added as part of the below PR? While I was debugging, the config parameters were being set in the code properly but the issue was being observed only in the Charles proxy as mentioned in the issue. 

https://github.com/microsoft/cpp_client_telemetry/pull/1005

cc: @aamittal1989

**Comment by lalitb** [comment]
> Was there any fix added as part of the below PR?

@nishchith-cp  - This PR is to validate that the multiple log managers are supported by 1ds cpp SDK. There is no fix.

**Comment by nishchith-cp** [comment]
The `_wrappedConfiguration` object is pointing to the same address for all the LogManagers that are created through the API. Hence the most recent configuration is getting updated to all the LogManagers that are created using this same API
`+(nullable ODWLogger *)loggerWithTenant:(nonnull NSString *)tenantToken
                  source:(nonnull NSString *)source
                  withConfig:(nonnull ODWLogConfiguration *)config`
                  
                 
<img width="770" alt="Screenshot 2022-05-27 at 3 06 41 PM" src="https://user-images.githubusercontent.com/85876413/170673656-8f3d1840-54c3-41ef-8439-1b6f962dabbb.png">

**Comment by lalitb** [comment]
@nishchith-cp Thanks for debugging the issue. With your better understanding of the issue and Obj-C knowledge, wondering if you would like to contribute to the fix. @eduardo-camacho and other maintainers can help review the change. This will also further help drive 1ds as a community-driven SDK.

**Comment by lalitb** [comment]
@nishchith-cp - You can refer to https://microsoft.sharepoint.com/teams/1ds.sdk.cpp/SitePages/Home.aspx `Want to Contribute` to get access.

**Comment by eduardo-camacho** [comment]
Thanks @nishchith-cp for looking into this. Regarding proposed solution, if the issue is on line 315 (because static), then the right fix would be to not have it as static, and caller taking ownership of returned ODWLogConfiguration object (wrapping object); you might not actually need to keep a static collection.
@lalitb FYI

**Comment by lalitb** [comment]
I agree with @eduardo-camacho solution above. The application should manage the lifetime of the returned ODWLogConfiguration. 
cc @sid-dahiya @kindbe as we discussed this solution in this week community meeting.

**Comment by nishchith-cp** [comment]
@lalitb @eduardo-camacho Below code fixed the issue. I will raise a PR for the same.
Now every time a new copy of the config object will be returned. I have tested for the changes and it looks good.

```
+(nullable ODWLogConfiguration *)getLogConfigurationCopy
{
    auto& config = LogManager::GetLogConfiguration();
    auto configCopy = new ILogConfiguration(config);
    return [[ODWLogConfiguration alloc] initWithILogConfiguration: configCopy];
}

```

<img width="795" alt="Screenshot 2022-06-06 at 1 35 28 PM" src="https://user-images.githubusercontent.com/85876413/172762679-c032942f-c586-4ed5-8978-4492d28f1340.png">

**Comment by eduardo-camacho** [comment]
Thanks, looking forward to PR

**Comment by nishchith-cp** [comment]
@eduardo-camacho @lalitb @sid-dahiya Please review the PR
https://github.com/microsoft/cpp_client_telemetry/pull/1021

**Comment by nishchith-cp** [comment]
Changes merged. Closing the issue. Thank you all for the support.

**Comment by nishchith-cp** [comment]
Even the below changes are needed for data to go to the correct cluster.
https://github.com/microsoft/cpp_client_telemetry/issues/825
