### ISSUE TITLE
Android Lint issues warning for Android_ID usage

### ISSUE THREAD

**Issue by Garima-Gupta1** [microsoft/cpp_client_telemetry#992]
Android Lint reports issue : Using `getString` to get device identifiers is not recommended in httpclient.java for Settings.Secure.ANDROID_ID

**Comment by lalitb** [comment]
@Garima-Gupta1 - This issue is self-assigned to you. Do you have plans to fix it?

**Comment by lalitb** [comment]
@Garima-Gupta1  - Gentle reminder, do you have plans to fix this ?

**Comment by Garima-Gupta1** [comment]
@lalitb , yes, I am working on this. We are noticing some changes in the latest lint configuration for office and I am analyzing the impact of the same on this bug to see if it is still an issue in office context.

**Comment by Garima-Gupta1** [comment]
Verified in Office Enlistment, Hardware Ids are not being flagged as part of latest lint configuration. Hence closing this bug.
