### ISSUE TITLE
The lib modules doesn't seem to exist? cpp_client_telemetry_modules ? 

### ISSUE THREAD

**Issue by namrog84** [microsoft/cpp_client_telemetry#996]
**Describe your environment.** Describe any aspect of your environment relevant to the problem, including your SDK version, platform, OS version, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

The main branch references some git module to another repo in libs/modules I think to cpp_client_telemetry_modules
Possibly to https://github.com/microsoft/cpp_client_telemetry_modules/ but that repo doesn't exist?  So when loading the solution I end up seeing errors for vcxitems not found in lib/modules such as lib/modules/dataviewer

**Steps to reproduce.**
Look at submodule/subtree in libs/module  and notice solution errors on opening.

**What is the expected behavior?**
For it to be there and accessible.

**What is the actual behavior?**
Nothing

**Additional context.**
Delete references to existent submodule or add back possibly deleted git repo for submodule/subtree?

**Comment by lalitb** [comment]
@namrog84 You need to be part of Microsoft org in Github to be able to access https://github.com/microsoft/cpp_client_telemetry_modules/.
Please try loading Solution after joining the Microsoft Org in github.

**Comment by lalitb** [comment]
@namrog84 - Do you have further questions based on above comment?

**Comment by adamgorMSFT** [comment]
I was able to switch to my Microsoft org github account and access it.

Thank you!
