### ISSUE TITLE
Support for multiple 1DS SDK frameworks in a single iOS app?

### ISSUE THREAD

**Issue by chadseippel** [microsoft/cpp_client_telemetry#998]
Hello!

I'm on the Intune MAM iOS team, and we're exploring options to package the 1DS SDK into our [Intune MAM SDK](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios) that we publicly release to iOS app partners. 

One scenario we're potentially concerned with is if a partner app integrates our Intune MAM SDK (with 1DS inside) as well as integrate the 1DS SDK separately into their app. Would there be issues having two versions of the 1DS SDK inside an iOS app? Such as both cacheing into the same keychain location. Or is this a supported scenario?

**Comment by lalitb** [comment]
@eduardo-camacho mentioned in today's community meeting that this scenario ( of using multiple 1ds sdk's within ios app ) is also used in office telemetry, so it is supported.

**Comment by lalitb** [comment]
closing as stated above.
